spring:
  datasource:
    username: springstudent
    url: jdbc:mysql://localhost:3306/web_customer_tracker
    password: springstudent
  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: n8XiGjoKjjxV7_5dkCoBdR-D
            client-id: 213413807511-fdvohf41qupuv21dmaj8nju3g9p8s7bl.apps.googleusercontent.com
    jwt:
      secretkey: DUCPHKEY
  jpa:
    show-sql: 'true'
